#!/bin/bash

USAGE_STR="Usage: jcc [-h | --help][-S][--lex | --parse | --codegen] path/to/code.c"

# Parse cli options
OUTPUT_ASSEMBLY=0

# Pass stage flag to compiler
COMPILER_STEP_FLAG=""

if ! vars=$(getopt -o Sh -l "lex,parse,codegen,help" -- "$@"); then
  exit 1
fi
for var in $vars
do
  case "$var" in
    "-S")
      OUTPUT_ASSEMBLY=1
      shift
      ;;
    "-h" | "--help")
      echo $USAGE_STR
      exit 1
      ;;
    "--") # marks end of opts. break from loop
      break
      ;;
    "--lex")
      COMPILER_STEP_FLAG="--lex"
      shift
      ;;
    "--parse")
      COMPILER_STEP_FLAG="--parse"
      shift
      ;;
    "--codegen")
      COMPILER_STEP_FLAG="--codegen"
      shift
      ;;
    *)
      echo "Unknown option detected"
      echo $USAGE_STR
      exit 1
      ;;
  esac
done

# Driver implementation for "Writing a C Compiler by Nora Sandler".
# Must accept as single argument - a path to a c source file in $1
if [ -z $1 ]; then
  echo $USAGE_STR
  exit 1
fi

INPUT_FILE=$1
BASE_PATH=$(echo $INPUT_FILE | sed -E 's/\.\w*$//')

# Preprocess input file
PREPROC_PATH="${BASE_PATH}.i"
gcc -E -P $INPUT_FILE -o $PREPROC_PATH

# Compile the preprocessed source code - stubbed out for now
ASSEMBLY_PATH="${BASE_PATH}.s"
if [ ! -e "./target/release/compiler" ]; then
  cargo build -r
fi
./target/release/compiler $PREPROC_PATH $COMPILER_STEP_FLAG
CODE=$?
if [ $CODE -ne 0 ]; then
  echo "Failed to compile program."
  exit $CODE
fi
rm $PREPROC_PATH

# If -S provided, stop after assembly output
if [ $OUTPUT_ASSEMBLY -eq 1 ]; then
  echo compiled assembly to $ASSEMBLY_PATH
  exit 0
fi

# Assemble and link assembly file
# BASE_PATH is the same as the path where the linked binary should live
gcc $ASSEMBLY_PATH -o $BASE_PATH
rm $ASSEMBLY_PATH

echo compiled executable to $BASE_PATH
exit 0

